# Librairies Python Numpy/Scipy

NumPy est une extension du langage de programmation Python, pour
manipuler des matrices ou des tableaux multidimensionnels.
Elle possède des fonctions mathématiques vectorielles opérant sur les tableaux.

NumPy est la base de la librairie SciPy, regroupement de librairies
Python pour le calcul scientifique. 

# Tableau unidimensionnel

In [ ]:
import numpy as np
a=np.arange(10)
print(a)
b = np.arange(0., 10., 0.499999999999)
print(b)

Pour obtenir le type de l'objet et celui des données sous-jacentes

In [ ]:
print(type(a))
print(a.dtype)

Pour créer un tableau de réels, il faut préciser le type explicitement

In [2]:
import numpy as np
a=np.arange(10, dtype='float')
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


La donnée membre shape retourne les dimensions du tableau sous la forme d'un tuple

In [ ]:
print(a.shape)

In [ ]:
M = np.zeros(shape=(2, 3))
print(M)
print('-'*20)
tup = M.shape
print(type(tup))
Nrows, Ncols = tup
print(Nrows, Ncols)

Application des opérateurs de calcul arithmétique

In [ ]:
print(a)
a=a+1      # ajout de 1 à tous les elements
print(a)
print('-'*20)
print(2*a) 
print(a*a) # carre de chaque element
print(a/a) # division element par element  DANGER

In [ ]:
a=np.array([0, 1, 2, 0, 2, 3, 5, 6, 6])
print(a.shape)
print(len(a))
print('valeurs   : ', a.min(), ' ', a.max())
print('positions : ', a.argmin(), ' ', a.argmax())

Pour transformer une liste python en numpy.ndarray, on appelle le constructeur ndarray 
ou la fonction membre asarray

In [ ]:
lst=list(range(10))
print(lst)
a=np.array(lst, dtype='float')
print(a)
a=np.asarray(lst, dtype='float') # plus efficace que le constructeur
print(a)

In [ ]:
a=np.linspace(0., 1., 10)
print(a)
print(len(a))

In [ ]:
a=np.linspace(0., 1., 10, endpoint=False)
print(a)
print(len(a))
help(np.linspace)

In [ ]:
#help(np.linspace)

# Tableau multidimensionnel
But : création d'un tableau vide 2x2 

In [4]:
import numpy as np
a=np.ndarray(shape=(2, 2)) # NON INITIALISE
print(a) 
print('--------------')
print(a.shape)
print('--------------')
print(a.ndim)

[[2.12199579e-314 4.67296746e-307]
 [6.22522714e-321 3.79442416e-321]]
--------------
(2, 2)
--------------
2


In [8]:
a.fill(0)
print(a)
print('-'*20)
a = np.zeros(shape=(2, 2), dtype=float)
print(a)
print('-'*20)

a[1, 1]=-1
print(a)

[[0. 0.]
 [0. 0.]]
--------------------
[[0. 0.]
 [0. 0.]]
--------------------
[[ 0.  0.]
 [ 0. -1.]]


In [9]:
print(a)
del a   # supprime l'objet a

a=np.empty(shape=(2, 2), dtype=float)
print(a.dtype)
print(a)
print(type(a))

[[ 0.  0.]
 [ 0. -1.]]
float64
[[ 0.  0.]
 [ 0. -1.]]
<class 'numpy.ndarray'>


In [ ]:
a=np.zeros(shape=(2, 2), dtype=float)
print(a.dtype)
print(a)
print(type(a))

bool
Boolean (True or False) stored as a bit

inti
Platform integer (normally either int32 or int64)

int8
Byte (-128 to 127)

int16
Integer (-32768 to 32767)

int32
Integer (-2^31 to 2^31 -1)

int64
Integer (-2^63 to 2 ^ 63 -1)

uint8
Unsigned integer (0 to 255)

uint16
Unsigned integer (0 to 65535)

uint32
Unsigned integer (0 to 2 ^ 32 - 1)

uint64
Unsigned integer (0 to 2 ^ 64 - 1)

float16
Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

float32
Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

float64 or float
Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

complex64
Complex number, represented by two 32-bit floats (real and imaginary components)

complex128 or complex
Complex number, represented by two 64-bit floats (real and imaginary components)

In [ ]:
a.fill(1)
print(a)

In [ ]:
z = 2. + 3.j
print(z)
#help(z)
print(abs(z))

## vue d'un tableau

In [11]:
import numpy as np
a=np.zeros(shape=(2, 2), dtype=float)
a.fill(1)

view=a  # ATTENTION shallow copy
print('meme objet : ', id(a), ' ==', id(view))

view[0, 0]=0  # modif de l'element [0, 0] de a !!!
print(a)
print('-'*20)
print(view)

meme objet :  2461544643056  == 2461544643056
[[0. 1.]
 [1. 1.]]
--------------------
[[0. 1.]
 [1. 1.]]


In [14]:
import numpy as np
a=np.zeros(shape=(2, 2), dtype=float)
a.fill(1)

c=a.copy()  # deep copy
print('meme objet : ', id(a), ' ==', id(c))

c[0, 0]=0  # modif de l'element [0, 0] de c n'a pas d'impact sur a
print(a)
print('-'*20)
print(c)

meme objet :  2461544643152  == 2461544643536
[[1. 1.]
 [1. 1.]]
--------------------
[[0. 1.]
 [1. 1.]]


# Comment savoir si un tableau numpy une copie ou une vue?
Soit deux tableaux numpy a et b.
a.base permet de savoir s'il a été construit à parti d'un autre objet de type numpy

si b est une vue complète ou partielle de a alors b.base retourne a.

Dans ce cas, b partage entièrement la mémoire de a. Ainsi np.shares_memory(a, b) retourne True.


In [18]:
import numpy as np
a=np.arange(10)
print('a : ', a)
print('a.base : ', a.base) # Base object if memory is from some other object

if a.base is None:
    print("il n'y a pas d'objet ayant servi à construire a")
    
b=a[0:4]
if b.base is a:
    print("a a servi à construire b")
    
c=a[4:]

c=a[4:].copy()
if c.base is a:
    print("a a servi à construire c")
 
print('\n === Partage mémoire ===')

print("a et b   ", np.shares_memory(a, b))
print("a et c   ", np.shares_memory(a, c))
print("b et c   ", np.shares_memory(b, c))

#b[0]=-1
#print(a)
b[3]=-100
print(b)
print(a)

a :  [0 1 2 3 4 5 6 7 8 9]
a.base :  None
il n'y a pas d'objet ayant servi à construire a
a a servi à construire b

 === Partage mémoire ===
a et b    True
a et c    False
b et c    False
[   0    1    2 -100]
[   0    1    2 -100    4    5    6    7    8    9]


# Découpage et indexage
## cas unidimensionnel
Le découpage (slicing) d'un tableau unidimensionnel NumPy est identique à celui d'une liste Python

In [19]:
import numpy as np
a=np.arange(10)
print(a)
# extraction des elements du tableau d'indice dans [3, 7)
print(a[3:7])  
 # extraction des elements avec un pas de 2 jusqu'a l'indice 8 exclu
print(a[:8:2])  
# renverse le tableau
print(a[::-1])   
print(a[-1::-1])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 2 4 6]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


## cas multidimensionnel

In [20]:
# tableau unidimensionnel retransformé en tableau 2x3x4
b=np.arange(24).reshape(2, 3, 4) 
print(b)
print('--------------')
print(b.shape)
print('--------------')
print(b.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------
(2, 3, 4)
--------------
3


On obtient 2 paquets, chacun formé d'une matrice 3x4

In [21]:
# on selectionne l'element placé en [0, 0] de tous les paquets
#view=b[:, 0, 0] 
#print(view)
# dans le paquet 0, on selectionne la ligne 0 
x=b[0, 0, :] 
print(x)
# dans le paquet 0, on selectionne dans la ligne 1 en se déplaçant de 2 en 2
#view=b[0, 1, ::2] 
#print(view)

[0 1 2 3]


In [22]:
x=b[0, 0, :] 
print("b et x   ", np.shares_memory(b, x))
print(x)
x[1] = 188
print(b)

b et x    True
[0 1 2 3]
[[[  0 188   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


In [ ]:
view=b[..., 1] # on selectionne la colonne 1 de tous les paquets
print(view)
print (view.base)

z = view.copy()
print(z.base)

## Exercice sur le slicing
Expliquer le comportement des cas suivants

In [24]:
print(b)
print('-'*20)
view=b[-1, ::-1, -1]
print(view)
view=b[0, ::-1, -1]
print(view)
view=b[0, :, -1]
print(view)

[[[  0 188   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]
--------------------
[23 19 15]
[11  7  3]
[ 3  7 11]


# Applatissage de tableaux (array flattening)

In [ ]:
b=np.arange(24).reshape(2, 3, 4)

flat_nd_copy=b.flatten()
print(flat_nd_copy)
flat_nd_copy[0]=-1
print(b)
print('------------------------------')
flat=b.ravel()  # nouvelle vue
print(flat)

flat[0]=-1  # modifie b
print(b)

# Concaténation de tableaux
Soient 2 tableaux A et B, comportant le même nombre de ligne, on désire construire le tableau augmenté A | B

In [25]:
A=np.arange(12).reshape(3, 4)
B = A.copy()
B=B+10
print(id(A))
print(id(B))
S=np.hstack((A, B))
print(S)

2461544641616
2461544974352
[[ 0  1  2  3 10 11 12 13]
 [ 4  5  6  7 14 15 16 17]
 [ 8  9 10 11 18 19 20 21]]


Autre approche avec np.concatenate

In [ ]:
np.concatenate((A, B), axis=1)

Généralisation suivant les autres directions

In [ ]:
A=np.arange(12).reshape(3, 4)
B=A
S=np.vstack((A, B))
print(S)
print('------------------')
S=np.dstack((A, B))
print(S)

## zero-padding - rolling

In [ ]:
A=np.arange(12).reshape(3, 4)
A=A+1
print(A)
print(type(A))

In [ ]:
lx=A.shape[0]
ly=A.shape[1]
A=np.pad(A, ((0, lx), (0, ly)), mode='constant') # (before, after)
print(A)
print('----------------------------')
A=np.roll(A, +ly//2, axis=1)
print(A)

Application du zero padding dans le calcul de produit de convolution

#  création d'une matrice
La classe matrix dérive de la classe ndarray

In [ ]:
A=np.matrix([[0, 1], [2, 3]])
print(type(A))

M=np.asmatrix(np.diag([2, 1]))
print(M)
print(type(M))

Création d'un vecteur

In [ ]:
print(A)
V=np.matrix([0, 1]).transpose()
print(V)
print('-'*30)
print(A*V)
